export const description = {
  title: 'Privacy Policy',
  subtitle: 'Last updated: April 20, 2024',
}

export const data = [
  {
    title: 'Introduction',
    content: (
      <>
        <p>
          Welcome to Adatag ("Adatag", "we", "us" and "our"), the platform
          offering NFT-based username (adatag) minting services through our
          website, adatag.io (hereinafter referred to as the "Service"). This
          Privacy Policy will help you understand how we collect, use and share
          your data and assist you in exercising the privacy rights available to
          you.
        </p>
        <p>
          This Privacy Policy is based on the{' '}
          <a href="https://www.termsfeed.com/public/uploads/2021/12/sample-privacy-policy-template.docx">
            <b>
              <u>TermsFeed's Privacy Policy Template</u>
            </b>
          </a>
          .
        </p>
        <p>
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used in this Privacy Policy have the same meanings
          as in our Terms and Conditions.
        </p>
      </>
    ),
  },
  {
    title: 'Definitions',
    content: (
      <>
        <h3>
          <b>Cookies</b>
        </h3>
        <p>
          Cookies are small files that are placed on Your computer, mobile
          device or any other device by a website, containing the details of
          Your browsing history on that website among its many uses.
        </p>

        <h3>
          <b>Service</b>
        </h3>
        <p>
          Service refers to the Adatag.io website, which allows users to mint
          unique, human-readable NFTs (non-fungible tokens) called "adatags" on
          the Cardano blockchain. These adatags can be used to identify a user's
          wallet for receiving funds and are decentralized, free, instant,
          public, and transparent.
        </p>

        <h3>
          <b>Personal Data</b>
        </h3>
        <p>
          For the purposes of GDPR, Personal Data means any information relating
          to You such as a name, an identification number, location data, online
          identifier or to one or more factors specific to the physical,
          physiological, genetic, mental, economic, cultural or social identity.
          For the purposes of the CCPA, Personal Data means any information that
          identifies, relates to, describes or is capable of being associated
          with, or could reasonably be linked, directly or indirectly, with You.
        </p>

        <h3>
          <b>Usage Data</b>
        </h3>
        <p>
          Usage Data refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for
          example, the duration of a page visit).
        </p>

        <h3>
          <b>You</b>
        </h3>
        <p>
          You means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable. Under GDPR (General
          Data Protection Regulation), You can be referred to as the Data
          Subject or as the User as you are the individual using the Service.
        </p>
      </>
    ),
  },
  {
    title: 'Types of Data Collected',
    content: (
      <>
        <h3>
          <b>Personal Data</b>
        </h3>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you ("Personal Data"). Personally identifiable information
          may include, but is not limited to:
        </p>
        <ul className="list-disc">
          <li>Wallet address</li>
          <li>Adatag username</li>
          <li>Time-lock deposit amount</li>
          <li>Transaction history</li>
        </ul>

        <h3>
          <b>Usage Data</b>
        </h3>
        <p>
          When you access the Service by or through a mobile device, we may
          collect certain information automatically, including, but not limited
          to, the type of mobile device you use, your mobile device unique ID,
          the IP address of your mobile device, your mobile operating system,
          the type of mobile Internet browser you use, unique device identifiers
          and other diagnostic data ("Usage Data").
        </p>

        <h3>
          <b>Tracking & Cookies Data</b>
        </h3>

        <p>
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </p>
        <p>
          Tracking technologies used are beacons, tags, and scripts to collect
          and track information and to improve and analyze Our Service. The
          technologies We use may include:
        </p>
        <ul className="list-disc">
          <li>
            <p>
              Cookies or Browser Cookies. A cookie is a small file placed on
              Your Device. You can instruct Your browser to refuse all Cookies
              or to indicate when a Cookie is being sent. However, if You do not
              accept Cookies, You may not be able to use some parts of our
              Service. Unless you have adjusted Your browser setting so that it
              will refuse Cookies, our Service may use Cookies.
            </p>
          </li>
          <li>
            <p>
              Web Beacons. Certain sections of our Service and our emails may
              contain small electronic files known as web beacons (also referred
              to as clear gifs, pixel tags, and single-pixel gifs) that permit
              the Company, for example, to count users who have visited those
              pages or opened an email and for other related website statistics
              (for example, recording the popularity of a certain section and
              verifying system and server integrity).
            </p>
          </li>
        </ul>
        <p>
          Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
          remain on Your personal computer or mobile device when You go offline,
          while Session Cookies are deleted as soon as You close Your web
          browser.
        </p>
        <p>
          We use both Session and Persistent Cookies for the purposes set out
          below:
        </p>
        <ul className="list-disc">
          <li>
            <p>
              Necessary / Essential Cookies (Session Cookies): These Cookies are
              essential to provide You with services available through the
              Website and to enable You to use some of its features. They help
              to authenticate users and prevent fraudulent use of user accounts.
              Without these Cookies, the services that You have asked for cannot
              be provided, and We only use these Cookies to provide You with
              those services.
            </p>
          </li>
          <li>
            <p>
              Cookies Policy / Notice Acceptance Cookies (Persistent Cookies):
              These Cookies identify if users have accepted the use of cookies
              on the Website.
            </p>
          </li>
          <li>
            <p>
              Functionality Cookies (Persistent Cookies): These Cookies allow us
              to remember choices You make when You use the Website, such as
              remembering your login details or language preference. The purpose
              of these Cookies is to provide You with a more personal experience
              and to avoid You having to re-enter your preferences every time
              You use the Website.
            </p>
          </li>
          <li>
            <p>
              Tracking and Performance Cookies (Persistent Cookies): These
              Cookies are used to track information about traffic to the Website
              and how users use the Website. The information gathered via these
              Cookies may directly or indirectly identify you as an individual
              visitor. This is because the information collected is typically
              linked to a pseudonymous identifier associated with the device you
              use to access the Website. We may also use these Cookies to test
              new pages, features or new functionality of the Website to see how
              our users react to them.
            </p>
          </li>
        </ul>
      </>
    ),
  },
  {
    title: 'Use of Data',
    content: (
      <>
        <p>Adatag uses the collected data for various purposes:</p>
        <ul className="list-disc">
          <li>To provide and maintain the Service</li>
          <li>To notify you about changes to our Service</li>
          <li>
            To allow you to participate in interactive features of our Service
            when you choose to do so
          </li>
          <li>To provide customer care and support</li>
          <li>
            To provide analysis or valuable information so that we can improve
            the Service
          </li>
          <li>To monitor the usage of the Service</li>
          <li>To detect, prevent and address technical issues</li>
        </ul>
      </>
    ),
  },
  {
    title: 'Transfer Of Data',
    content: (
      <>
        <p>
          Your information, including Personal Data, may be transferred to — and
          maintained on — computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ than those from your jurisdiction.
        </p>
        <p>
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          Adatag will take all steps reasonably necessary to ensure that your
          data is treated securely and in accordance with this Privacy Policy
          and no transfer of your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
      </>
    ),
  },
  {
    title: 'Disclosure Of Data',
    content: (
      <>
        <h3>
          <b>Legal Requirements</b>
        </h3>
        <p>
          Adatag may disclose your Personal Data in the good faith belief that
          such action is necessary to:
        </p>
        <ul className="list-disc">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of Adatag</li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            Protect the personal safety of Users of the Service or the public
          </li>
          <li>Protect against legal liability</li>
        </ul>
      </>
    ),
  },
  {
    title: 'Security Of Data',
    content: (
      <>
        <p>
          The security of your data is important to us, but remember that no
          method of transmission over the Internet, or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
      </>
    ),
  },
  {
    title:
      'Your Data Protection Rights Under General Data Protection Regulation (GDPR)',
    content: (
      <>
        <p>
          If you are a resident of the European Economic Area (EEA), you have
          certain data protection rights. Adatag aims to take reasonable steps
          to allow you to correct, amend, delete, or limit the use of your
          Personal Data.
        </p>
        <p>
          If you wish to be informed what Personal Data we hold about you and if
          you want it to be removed from our systems, please contact us.
        </p>
        <p>
          In certain circumstances, you have the following data protection
          rights:
        </p>
        <ul className="list-disc">
          <li>
            <p>
              The right to access, update or to delete the information we have
              on you. Whenever made possible, you can access, update or request
              deletion of your Personal Data directly within your account
              settings section. If you are unable to perform these actions
              yourself, please contact us to assist you.
            </p>
          </li>
          <li>
            <p>
              The right of rectification. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete.
            </p>
          </li>
          <li>
            <p>
              The right to object. You have the right to object to our
              processing of your Personal Data.
            </p>
          </li>
          <li>
            <p>
              The right of restriction. You have the right to request that we
              restrict the processing of your personal information.
            </p>
          </li>
          <li>
            <p>
              The right to data portability. You have the right to be provided
              with a copy of the information we have on you in a structured,
              machine-readable and commonly used format.
            </p>
          </li>
          <li>
            <p>
              The right to withdraw consent. You also have the right to withdraw
              your consent at any time where Adatag relied on your consent to
              process your personal information.
            </p>
          </li>
        </ul>
        <p>
          Please note that we may ask you to verify your identity before
          responding to such requests.
        </p>
        <p>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </p>
      </>
    ),
  },
  {
    title: 'Service Providers',
    content: (
      <>
        <p>
          We may employ third party companies and individuals to facilitate our
          Service ("Service Providers"), to provide the Service on our behalf,
          to perform Service-related services or to assist us in analyzing how
          our Service is used.
        </p>
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>
      </>
    ),
  },
  {
    title: 'Analytics',
    content: (
      <>
        <p>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
        </p>
        <h3>
          <b>Google Analytics</b>
        </h3>
        <p>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic. Google uses the data collected to
          track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to
          contextualize and personalize the ads of its own advertising network.
        </p>
        <p>
          You can opt-out of having made your activity on the Service available
          to Google Analytics by installing the Google Analytics opt-out browser
          add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
          analytics.js, and dc.js) from sharing information with Google
          Analytics about visits activity.
        </p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy & Terms web page:
          <a
            href="http://www.google.com/intl/en/policies/privacy/"
            target="_blank"
            rel="noopener noreferrer"
          >
            http://www.google.com/intl/en/policies/privacy/
          </a>
        </p>
      </>
    ),
  },
  {
    title: 'Links To Other Sites',
    content: (
      <>
        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click on a third party link, you will be directed to that
          third party's site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
      </>
    ),
  },
  {
    title: "Children's Privacy",
    content: (
      <>
        <p>
          Our Service does not address anyone under the age of 18 ("Children").
        </p>
        <p>
          We do not knowingly collect personally identifiable information from
          anyone under the age of 18. If you are a parent or guardian and you
          are aware that your Children has provided us with Personal Data,
          please contact us. If we become aware that we have collected Personal
          Data from children without verification of parental consent, we take
          steps to remove that information from our servers.
        </p>
      </>
    ),
  },
  {
    title: 'Changes To This Privacy Policy',
    content: (
      <>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update the
          "effective date" at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
      </>
    ),
  },
  {
    title: 'Contact Us',
    content: (
      <>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul>
          <li>
            By email:{' '}
            <a
              href="mailto:hello@adatag.io"
              target="_blank"
              rel="noopener noreferrer"
            >
              <b>
                <u>
                  <i>hello@adatag.io</i>
                </u>
              </b>
            </a>
          </li>
        </ul>
      </>
    ),
  },
]
