name = "adatag/aiken"
version = "0.2.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for @adatag project"

[repository]
user = "ilap"
project = "adatag"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[config]
