name = "adatag/aiken"
version = "0.1.0"
license = "Apache-2.0"
description = "Aiken contracts for @adatag project"

[repository]
user = "ilap"
project = "adatag"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
