version: "3.9"
services:
  yaci-cli:
    image: bloxbean/yaci-cli:0.0.19
    ports:
      - "${HOST_N2N_PORT}:3001"
      - "${HOST_N2C_SOCAT_PORT}:3333"
      - "${HOST_SUBMIT_API_PORT}:8090"
      - "${HOST_STORE_API_PORT}:8080"
      - "${HOST_CLUSTER_API_PORT}:10000"
      - "${HOST_OGMIOS_PORT}:1337"
      - "${HOST_KUPO_PORT}:1442"
    volumes:
      - cluster-data:/clusters
    env_file: 
      - env
    entrypoint: ${YACI_CLI_CMD}
     # - sleep
     # - infinity

  yaci-viewer:
    image: bloxbean/yaci-viewer:0.0.8
    ports:
      - "${HOST_VIEWER_PORT}:5173"
    env_file: 
      - env

volumes:
  cluster-data:
